#!/usr/bin/env python
import sys

write = sys.stdout.write

for i in range(1):
    for j in range(30, 38):
        for k in range(40, 48):
            bullet = "\xe2\x80\xa2"
            markers = " %s%s%s " % (bullet, bullet, bullet)
            # write("\33[%d;%d;%dm%d;%d;%d\33[m " % (i, j, k, i, j, k))
            write("\33[%d;%d;%dm %s \33[m " % (i, j, k, markers))
        write("\n")
