#
# ZSH Configuration
# Version 3.0.2
#
#
# Licensed under WTFPL
# Copyright (c) 2016 Jaggy Gauran
# https://jag.gy
#
### ZSH Specific Configuration
#####################################################################
ZSH=$HOME/.oh-my-zsh

# Good themes: awesomepanda, cloud, daveverwer, fwalch, miloshadzic, mrtazz, nanotech, spaceship
# If we're using fwalch, delete the space since it's annoying.
ZSH_THEME="mrtazz"
CASE_SENSITIVE="true"         # Remove case sensitive autocorrection
DISABLE_AUTO_TITLE=true
DISABLE_CORRECTION="true"     # Disable autocorrection when executing commands
DEFAULT_USER="jaggy"          # This is to make certain themes look prettier
setopt HIST_IGNORE_SPACE      # Do not log commands prefixed with a space


### Shell Config
#####################################################################
plugins=(git laravel)
stty -ixon                   # Removing the bindings from Ctrl-S
export KEYTIMEOUT=1          # kill the timeout when pressing escape
export LC_ALL=en_US.UTF-8    # Fix ZSH and Tmux issues
export LANG="$LC_ALL"
export VISUAL="nvim"         # Use nvim for everything
export EDITOR="$VISUAL"
export TERM=screen-256color  # Font rendering and colors for the terminal
export USE_SPACEMACS="1";
# export TERM=xterm-256color-italic # Font rendering and colors for the terminal

### Exports
#####################################################################

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/zsh/aliases.zsh
source $HOME/.dotfiles/zsh/completion/tmuxinator.zsh
source $HOME/.dotfiles/zsh/completion/ssh.zsh
eval "$(/opt/homebrew/bin/brew shellenv)"
source `brew --prefix`/etc/profile.d/z.sh

### Environment
###  Commands take order of precedence so if you want a native comamnd
###  Make sure you append the $PATH
#####################################################################

export NPM_PACKAGES="${HOME}/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

# export CYCLES_OPENCL_TEST=all
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin

PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
PATH=$HOME/.bin:$PATH
PATH=$HOME/.dotfiles/scripts:$PATH                                       # Load the dotfile scripts.
PATH=/usr/local/php5/bin:$HOME/.composer/vendor/bin:$PATH                # PHP Specific
PATH=vendor/bin/:$PATH                                                   # Relative Paths
PATH=$HOME/.rvm/bin:$PATH                                                # Ruby
PATH="/usr/local/Cellar/python3/3.5.2_1/bin:$PATH"                                # Python Libraries
PATH="$NPM_PACKAGES/bin:$PATH"

# PATH="$HOME/Applications/blender.app/Contents/MacOS:$PATH"             # Blender
# PATH="$HOME/Library/Python/2.7/bin:$HOME/Library/Python/3.5/bin:$PATH" # Python Libraries

bindkey "^D" beginning-of-line
bindkey "^E" end-of-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word

export FZF_DEFAULT_COMMAND='ag --files-with-matches --ignore-case --hidden'
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export NVIM_TUI_ENABLE_CURSOR_SHAPE=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Tiny Care Terminal Twitter API
# https://github.com/notwaldorf/tiny-care-terminal
if [ -f ~/.dotfiles/zsh/tiny-care-terminal.zsh ]; then
    source ~/.dotfiles/zsh/tiny-care-terminal.zsh
fi

export TTC_REPOS="/Users/jaggy/code"
export TTC_REPOS_DEPTH=1
export TTC_GITBOT="gitlog"
export TTC_WEATHER="Manila"
export TTC_CELSIUS=true
export TTC_APIKEYS=true
export TTC_UPDATE_INTERVAL=20
export TTC_TERMINAL_TITLE=false
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"

if [ -f "$HOME/.zsh_private" ]; then
    source $HOME/.zsh_private
fi
